# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainForm(object):
    def setupUi(self, mainForm):
        mainForm.setObjectName("mainForm")
        mainForm.resize(1063, 872)
        self.gridLayout = QtWidgets.QGridLayout(mainForm)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widgetTop = QtWidgets.QWidget(mainForm)
        self.widgetTop.setMinimumSize(QtCore.QSize(0, 60))
        self.widgetTop.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widgetTop.setStyleSheet("")
        self.widgetTop.setObjectName("widgetTop")
        self.btnSearch = QtWidgets.QPushButton(self.widgetTop)
        self.btnSearch.setGeometry(QtCore.QRect(640, 10, 91, 41))
        self.btnSearch.setObjectName("btnSearch")
        self.txtSearchword = QtWidgets.QLineEdit(self.widgetTop)
        self.txtSearchword.setGeometry(QtCore.QRect(310, 9, 311, 41))
        self.txtSearchword.setObjectName("txtSearchword")
        self.gridLayout.addWidget(self.widgetTop, 0, 0, 1, 1)
        self.widgetMain = QtWidgets.QWidget(mainForm)
        self.widgetMain.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.widgetMain.setObjectName("widgetMain")
        self.gridLayout.addWidget(self.widgetMain, 1, 0, 1, 1)
        self.widgetTools = QtWidgets.QWidget(mainForm)
        self.widgetTools.setMinimumSize(QtCore.QSize(0, 30))
        self.widgetTools.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widgetTools.setStyleSheet("")
        self.widgetTools.setObjectName("widgetTools")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widgetTools)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnGetAllLinks = QtWidgets.QPushButton(self.widgetTools)
        self.btnGetAllLinks.setEnabled(False)
        self.btnGetAllLinks.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGetAllLinks.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnGetAllLinks.setObjectName("btnGetAllLinks")
        self.gridLayout_3.addWidget(self.btnGetAllLinks, 0, 0, 1, 1)
        self.btnOpenSource = QtWidgets.QPushButton(self.widgetTools)
        self.btnOpenSource.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpenSource.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnOpenSource.setObjectName("btnOpenSource")
        self.gridLayout_3.addWidget(self.btnOpenSource, 0, 2, 1, 1)
        self.lblLastPlayEpisodeName = QtWidgets.QLabel(self.widgetTools)
        self.lblLastPlayEpisodeName.setObjectName("lblLastPlayEpisodeName")
        self.gridLayout_3.addWidget(self.lblLastPlayEpisodeName, 0, 5, 1, 1)
        self.lblSpace02 = QtWidgets.QLabel(self.widgetTools)
        self.lblSpace02.setText("")
        self.lblSpace02.setObjectName("lblSpace02")
        self.gridLayout_3.addWidget(self.lblSpace02, 0, 8, 1, 1)
        self.lblLastPlay = QtWidgets.QLabel(self.widgetTools)
        self.lblLastPlay.setObjectName("lblLastPlay")
        self.gridLayout_3.addWidget(self.lblLastPlay, 0, 4, 1, 1)
        self.btnAbout = QtWidgets.QPushButton(self.widgetTools)
        self.btnAbout.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAbout.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnAbout.setObjectName("btnAbout")
        self.gridLayout_3.addWidget(self.btnAbout, 0, 1, 1, 1)
        self.lblLastPlayEpisodeNum = QtWidgets.QLabel(self.widgetTools)
        self.lblLastPlayEpisodeNum.setObjectName("lblLastPlayEpisodeNum")
        self.gridLayout_3.addWidget(self.lblLastPlayEpisodeNum, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(828, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.lblSpace01 = QtWidgets.QLabel(self.widgetTools)
        self.lblSpace01.setText("")
        self.lblSpace01.setObjectName("lblSpace01")
        self.gridLayout_3.addWidget(self.lblSpace01, 0, 6, 1, 1)
        self.gridLayout.addWidget(self.widgetTools, 2, 0, 1, 1)
        self.widgetConsole = QtWidgets.QWidget(mainForm)
        self.widgetConsole.setMinimumSize(QtCore.QSize(0, 180))
        self.widgetConsole.setMaximumSize(QtCore.QSize(16777215, 180))
        self.widgetConsole.setObjectName("widgetConsole")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetConsole)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.console1 = QtWidgets.QPlainTextEdit(self.widgetConsole)
        self.console1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"微软雅黑\";")
        self.console1.setReadOnly(True)
        self.console1.setPlainText("")
        self.console1.setObjectName("console1")
        self.gridLayout_2.addWidget(self.console1, 0, 0, 1, 1)
        self.console2 = QtWidgets.QPlainTextEdit(self.widgetConsole)
        self.console2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"微软雅黑\";")
        self.console2.setReadOnly(True)
        self.console2.setPlainText("")
        self.console2.setObjectName("console2")
        self.gridLayout_2.addWidget(self.console2, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widgetConsole, 3, 0, 1, 1)

        self.retranslateUi(mainForm)
        QtCore.QMetaObject.connectSlotsByName(mainForm)

    def retranslateUi(self, mainForm):
        _translate = QtCore.QCoreApplication.translate
        mainForm.setWindowTitle(_translate("mainForm", "看番神器"))
        self.btnSearch.setText(_translate("mainForm", "搜索"))
        self.btnGetAllLinks.setText(_translate("mainForm", "抓取链接"))
        self.btnOpenSource.setText(_translate("mainForm", "项目地址"))
        self.lblLastPlayEpisodeName.setText(_translate("mainForm", "无"))
        self.lblLastPlay.setText(_translate("mainForm", "最近一次播放："))
        self.btnAbout.setText(_translate("mainForm", "关于"))
        self.lblLastPlayEpisodeNum.setText(_translate("mainForm", "第0集"))
