# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form_mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainForm(object):
    def setupUi(self, mainForm):
        mainForm.setObjectName("mainForm")
        mainForm.resize(953, 800)
        self.gridLayout_4 = QtWidgets.QGridLayout(mainForm)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(mainForm)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageWelcome = QtWidgets.QWidget()
        self.pageWelcome.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pageWelcome.setObjectName("pageWelcome")
        self.label = QtWidgets.QLabel(self.pageWelcome)
        self.label.setGeometry(QtCore.QRect(230, 130, 431, 191))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.pageWelcome)
        self.pageSearchResult = QtWidgets.QWidget()
        self.pageSearchResult.setStyleSheet("")
        self.pageSearchResult.setObjectName("pageSearchResult")
        self.gridLayout = QtWidgets.QGridLayout(self.pageSearchResult)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.pageSearchResult)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll = QtWidgets.QWidget()
        self.scroll.setGeometry(QtCore.QRect(0, 0, 81, 28))
        self.scroll.setObjectName("scroll")
        self.grid = QtWidgets.QGridLayout(self.scroll)
        self.grid.setSpacing(9)
        self.grid.setObjectName("grid")
        self.scrollArea.setWidget(self.scroll)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageSearchResult)
        self.pageDetail = QtWidgets.QWidget()
        self.pageDetail.setObjectName("pageDetail")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pageDetail)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widgetTop_2 = QtWidgets.QWidget(self.pageDetail)
        self.widgetTop_2.setMinimumSize(QtCore.QSize(0, 300))
        self.widgetTop_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.widgetTop_2.setObjectName("widgetTop_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widgetTop_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widgetDesc = QtWidgets.QWidget(self.widgetTop_2)
        self.widgetDesc.setStyleSheet("")
        self.widgetDesc.setObjectName("widgetDesc")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widgetDesc)
        self.gridLayout_7.setContentsMargins(12, -1, -1, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblStars = QtWidgets.QLabel(self.widgetDesc)
        self.lblStars.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblStars.setObjectName("lblStars")
        self.gridLayout_7.addWidget(self.lblStars, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widgetDesc)
        self.label_9.setMinimumSize(QtCore.QSize(0, 28))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widgetDesc)
        self.label_6.setMinimumSize(QtCore.QSize(0, 28))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widgetDesc)
        self.label_7.setMinimumSize(QtCore.QSize(0, 28))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widgetDesc)
        self.label_5.setMinimumSize(QtCore.QSize(40, 28))
        self.label_5.setMaximumSize(QtCore.QSize(40, 28))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.lblTitle = QtWidgets.QLabel(self.widgetDesc)
        self.lblTitle.setMinimumSize(QtCore.QSize(0, 50))
        self.lblTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lblTitle.setStyleSheet("font: 16pt \"微软雅黑\";")
        self.lblTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout_7.addWidget(self.lblTitle, 0, 0, 1, 2)
        self.lblTime = QtWidgets.QLabel(self.widgetDesc)
        self.lblTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblTime.setObjectName("lblTime")
        self.gridLayout_7.addWidget(self.lblTime, 2, 1, 1, 1)
        self.lblType = QtWidgets.QLabel(self.widgetDesc)
        self.lblType.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblType.setObjectName("lblType")
        self.gridLayout_7.addWidget(self.lblType, 3, 1, 1, 1)
        self.lblArea = QtWidgets.QLabel(self.widgetDesc)
        self.lblArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblArea.setObjectName("lblArea")
        self.gridLayout_7.addWidget(self.lblArea, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.widgetDesc, 0, 2, 1, 1)
        self.lblCover = QtWidgets.QLabel(self.widgetTop_2)
        self.lblCover.setMinimumSize(QtCore.QSize(210, 300))
        self.lblCover.setMaximumSize(QtCore.QSize(210, 300))
        self.lblCover.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.lblCover.setText("")
        self.lblCover.setObjectName("lblCover")
        self.gridLayout_6.addWidget(self.lblCover, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widgetTop_2)
        self.label_3.setMinimumSize(QtCore.QSize(8, 0))
        self.label_3.setMaximumSize(QtCore.QSize(8, 16777215))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widgetTop_2, 0, 0, 1, 1)
        self.widgetBottom = QtWidgets.QWidget(self.pageDetail)
        self.widgetBottom.setStyleSheet("")
        self.widgetBottom.setObjectName("widgetBottom")
        self.gridLayout_5.addWidget(self.widgetBottom, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageDetail)
        self.pageNoResult = QtWidgets.QWidget()
        self.pageNoResult.setObjectName("pageNoResult")
        self.label_2 = QtWidgets.QLabel(self.pageNoResult)
        self.label_2.setGeometry(QtCore.QRect(340, 170, 291, 151))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.pageNoResult)
        self.gridLayout_4.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.widgetTop = QtWidgets.QWidget(mainForm)
        self.widgetTop.setMinimumSize(QtCore.QSize(0, 60))
        self.widgetTop.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widgetTop.setStyleSheet("")
        self.widgetTop.setObjectName("widgetTop")
        self.btnSearch = QtWidgets.QPushButton(self.widgetTop)
        self.btnSearch.setGeometry(QtCore.QRect(640, 10, 91, 41))
        self.btnSearch.setObjectName("btnSearch")
        self.txtSearchword = QtWidgets.QLineEdit(self.widgetTop)
        self.txtSearchword.setGeometry(QtCore.QRect(310, 9, 311, 41))
        self.txtSearchword.setObjectName("txtSearchword")
        self.btnBack = QtWidgets.QPushButton(self.widgetTop)
        self.btnBack.setGeometry(QtCore.QRect(770, 20, 75, 23))
        self.btnBack.setObjectName("btnBack")
        self.gridLayout_4.addWidget(self.widgetTop, 0, 0, 1, 1)
        self.widgetTools = QtWidgets.QWidget(mainForm)
        self.widgetTools.setMinimumSize(QtCore.QSize(0, 30))
        self.widgetTools.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widgetTools.setStyleSheet("")
        self.widgetTools.setObjectName("widgetTools")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widgetTools)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnGetAllLinks = QtWidgets.QPushButton(self.widgetTools)
        self.btnGetAllLinks.setEnabled(False)
        self.btnGetAllLinks.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGetAllLinks.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnGetAllLinks.setObjectName("btnGetAllLinks")
        self.gridLayout_3.addWidget(self.btnGetAllLinks, 0, 0, 1, 1)
        self.btnOpenSource = QtWidgets.QPushButton(self.widgetTools)
        self.btnOpenSource.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpenSource.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnOpenSource.setObjectName("btnOpenSource")
        self.gridLayout_3.addWidget(self.btnOpenSource, 0, 2, 1, 1)
        self.lblLastPlayEpisodeName = QtWidgets.QLabel(self.widgetTools)
        self.lblLastPlayEpisodeName.setObjectName("lblLastPlayEpisodeName")
        self.gridLayout_3.addWidget(self.lblLastPlayEpisodeName, 0, 5, 1, 1)
        self.lblSpace02 = QtWidgets.QLabel(self.widgetTools)
        self.lblSpace02.setText("")
        self.lblSpace02.setObjectName("lblSpace02")
        self.gridLayout_3.addWidget(self.lblSpace02, 0, 8, 1, 1)
        self.lblLastPlay = QtWidgets.QLabel(self.widgetTools)
        self.lblLastPlay.setObjectName("lblLastPlay")
        self.gridLayout_3.addWidget(self.lblLastPlay, 0, 4, 1, 1)
        self.btnAbout = QtWidgets.QPushButton(self.widgetTools)
        self.btnAbout.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAbout.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnAbout.setObjectName("btnAbout")
        self.gridLayout_3.addWidget(self.btnAbout, 0, 1, 1, 1)
        self.lblLastPlayEpisodeNum = QtWidgets.QLabel(self.widgetTools)
        self.lblLastPlayEpisodeNum.setObjectName("lblLastPlayEpisodeNum")
        self.gridLayout_3.addWidget(self.lblLastPlayEpisodeNum, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(828, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.lblSpace01 = QtWidgets.QLabel(self.widgetTools)
        self.lblSpace01.setText("")
        self.lblSpace01.setObjectName("lblSpace01")
        self.gridLayout_3.addWidget(self.lblSpace01, 0, 6, 1, 1)
        self.gridLayout_4.addWidget(self.widgetTools, 2, 0, 1, 1)
        self.widgetConsole = QtWidgets.QWidget(mainForm)
        self.widgetConsole.setMinimumSize(QtCore.QSize(0, 180))
        self.widgetConsole.setMaximumSize(QtCore.QSize(16777215, 180))
        self.widgetConsole.setObjectName("widgetConsole")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetConsole)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.console1 = QtWidgets.QPlainTextEdit(self.widgetConsole)
        self.console1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"微软雅黑\";")
        self.console1.setReadOnly(True)
        self.console1.setPlainText("")
        self.console1.setObjectName("console1")
        self.gridLayout_2.addWidget(self.console1, 0, 0, 1, 1)
        self.console2 = QtWidgets.QPlainTextEdit(self.widgetConsole)
        self.console2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 12pt \"微软雅黑\";")
        self.console2.setReadOnly(True)
        self.console2.setPlainText("")
        self.console2.setObjectName("console2")
        self.gridLayout_2.addWidget(self.console2, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widgetConsole, 3, 0, 1, 1)

        self.retranslateUi(mainForm)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainForm)

    def retranslateUi(self, mainForm):
        _translate = QtCore.QCoreApplication.translate
        mainForm.setWindowTitle(_translate("mainForm", "看番神器"))
        self.label.setText(_translate("mainForm", "WELCOME"))
        self.lblStars.setText(_translate("mainForm", "演员："))
        self.label_9.setText(_translate("mainForm", "演员："))
        self.label_6.setText(_translate("mainForm", "类型："))
        self.label_7.setText(_translate("mainForm", "年代："))
        self.label_5.setText(_translate("mainForm", "地区："))
        self.lblTitle.setText(_translate("mainForm", "标题"))
        self.lblTime.setText(_translate("mainForm", "年代"))
        self.lblType.setText(_translate("mainForm", "类型"))
        self.lblArea.setText(_translate("mainForm", "地区"))
        self.label_2.setText(_translate("mainForm", "啥都没有"))
        self.btnSearch.setText(_translate("mainForm", "搜索"))
        self.btnBack.setText(_translate("mainForm", "返回"))
        self.btnGetAllLinks.setText(_translate("mainForm", "抓取链接"))
        self.btnOpenSource.setText(_translate("mainForm", "项目地址"))
        self.lblLastPlayEpisodeName.setText(_translate("mainForm", "无"))
        self.lblLastPlay.setText(_translate("mainForm", "最近一次播放："))
        self.btnAbout.setText(_translate("mainForm", "关于"))
        self.lblLastPlayEpisodeNum.setText(_translate("mainForm", "第0集"))
