# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainForm(object):
    def setupUi(self, mainForm):
        mainForm.setObjectName("mainForm")
        mainForm.resize(1000, 800)
        mainForm.setMinimumSize(QtCore.QSize(960, 650))
        self.gridLayout_4 = QtWidgets.QGridLayout(mainForm)
        self.gridLayout_4.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widgetTools = QtWidgets.QWidget(mainForm)
        self.widgetTools.setMinimumSize(QtCore.QSize(0, 30))
        self.widgetTools.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widgetTools.setStyleSheet("")
        self.widgetTools.setObjectName("widgetTools")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widgetTools)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnGetAllLinks = QtWidgets.QPushButton(self.widgetTools)
        self.btnGetAllLinks.setEnabled(False)
        self.btnGetAllLinks.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGetAllLinks.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnGetAllLinks.setObjectName("btnGetAllLinks")
        self.gridLayout_3.addWidget(self.btnGetAllLinks, 0, 0, 1, 1)
        self.btnOpenSource = QtWidgets.QPushButton(self.widgetTools)
        self.btnOpenSource.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpenSource.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnOpenSource.setObjectName("btnOpenSource")
        self.gridLayout_3.addWidget(self.btnOpenSource, 0, 2, 1, 1)
        self.lblLastPlayEpisodeName = QtWidgets.QLabel(self.widgetTools)
        self.lblLastPlayEpisodeName.setObjectName("lblLastPlayEpisodeName")
        self.gridLayout_3.addWidget(self.lblLastPlayEpisodeName, 0, 5, 1, 1)
        self.lblSpace02 = QtWidgets.QLabel(self.widgetTools)
        self.lblSpace02.setText("")
        self.lblSpace02.setObjectName("lblSpace02")
        self.gridLayout_3.addWidget(self.lblSpace02, 0, 8, 1, 1)
        self.lblLastPlay = QtWidgets.QLabel(self.widgetTools)
        self.lblLastPlay.setObjectName("lblLastPlay")
        self.gridLayout_3.addWidget(self.lblLastPlay, 0, 4, 1, 1)
        self.btnAbout = QtWidgets.QPushButton(self.widgetTools)
        self.btnAbout.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAbout.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnAbout.setObjectName("btnAbout")
        self.gridLayout_3.addWidget(self.btnAbout, 0, 1, 1, 1)
        self.lblLastPlayEpisodeNum = QtWidgets.QLabel(self.widgetTools)
        self.lblLastPlayEpisodeNum.setObjectName("lblLastPlayEpisodeNum")
        self.gridLayout_3.addWidget(self.lblLastPlayEpisodeNum, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(828, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.lblSpace01 = QtWidgets.QLabel(self.widgetTools)
        self.lblSpace01.setText("")
        self.lblSpace01.setObjectName("lblSpace01")
        self.gridLayout_3.addWidget(self.lblSpace01, 0, 6, 1, 1)
        self.gridLayout_4.addWidget(self.widgetTools, 2, 0, 1, 1)
        self.widgetConsole = QtWidgets.QWidget(mainForm)
        self.widgetConsole.setMinimumSize(QtCore.QSize(0, 180))
        self.widgetConsole.setMaximumSize(QtCore.QSize(16777215, 180))
        self.widgetConsole.setObjectName("widgetConsole")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetConsole)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.console1 = QtWidgets.QPlainTextEdit(self.widgetConsole)
        self.console1.setStyleSheet("color: #ffffff;\n"
"background-color: #303038;\n"
"font: 12pt \"微软雅黑\";")
        self.console1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.console1.setReadOnly(True)
        self.console1.setPlainText("")
        self.console1.setObjectName("console1")
        self.gridLayout_2.addWidget(self.console1, 0, 0, 1, 1)
        self.console2 = QtWidgets.QPlainTextEdit(self.widgetConsole)
        self.console2.setStyleSheet("color: #ffffff;\n"
"background-color: #303038;\n"
"font: 12pt \"微软雅黑\";")
        self.console2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.console2.setReadOnly(True)
        self.console2.setPlainText("")
        self.console2.setObjectName("console2")
        self.gridLayout_2.addWidget(self.console2, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widgetConsole, 3, 0, 1, 1)
        self.widgetTop = QtWidgets.QWidget(mainForm)
        self.widgetTop.setMinimumSize(QtCore.QSize(0, 55))
        self.widgetTop.setMaximumSize(QtCore.QSize(16777215, 55))
        self.widgetTop.setStyleSheet("\n"
"background-color: #303038\n"
"/*\n"
"background-color: rgb(255, 255, 255)\n"
"\n"
"*/")
        self.widgetTop.setObjectName("widgetTop")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widgetTop)
        self.gridLayout_9.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btnBack = QtWidgets.QPushButton(self.widgetTop)
        self.btnBack.setStyleSheet("background-color: #ffffff;")
        self.btnBack.setObjectName("btnBack")
        self.gridLayout_9.addWidget(self.btnBack, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 0, 1, 1, 1)
        self.widgetSearch = QtWidgets.QWidget(self.widgetTop)
        self.widgetSearch.setMinimumSize(QtCore.QSize(400, 45))
        self.widgetSearch.setMaximumSize(QtCore.QSize(16777215, 45))
        self.widgetSearch.setStyleSheet("")
        self.widgetSearch.setObjectName("widgetSearch")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widgetSearch)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget = QtWidgets.QWidget(self.widgetSearch)
        self.widget.setStyleSheet("background-color: #393942;")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboSelectInterface = QtWidgets.QComboBox(self.widget)
        self.comboSelectInterface.setMinimumSize(QtCore.QSize(0, 40))
        self.comboSelectInterface.setMaximumSize(QtCore.QSize(100, 40))
        self.comboSelectInterface.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comboSelectInterface.setStyleSheet("QComboBox {\n"
"color: #bababa;\n"
"background:transparent;\n"
"font: 12pt \"微软雅黑\";\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"outline: 0px solid gray;\n"
"border: 1px solid #393942;\n"
"color: #bababa;\n"
"background-color: #393942;\n"
"selection-background-color: #7f7f7f;\n"
"}")
        self.comboSelectInterface.setObjectName("comboSelectInterface")
        self.comboSelectInterface.addItem("")
        self.comboSelectInterface.addItem("")
        self.horizontalLayout.addWidget(self.comboSelectInterface)
        self.gridLayout_8.addWidget(self.widget, 0, 1, 1, 1)
        self.btnSearch = QtWidgets.QPushButton(self.widgetSearch)
        self.btnSearch.setMinimumSize(QtCore.QSize(80, 40))
        self.btnSearch.setMaximumSize(QtCore.QSize(80, 40))
        self.btnSearch.setStyleSheet("QPushButton{\n"
"background-color: #44444f;\n"
"color: #ff5246;\n"
"border-top-right-radius : 20px;\n"
"border-bottom-right-radius : 20px;\n"
"font: 12pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ff5246;\n"
"color: #ffffff;\n"
"}\n"
"QPushButton:pressed{\n"
"color: #7f7f7f;\n"
"}")
        self.btnSearch.setObjectName("btnSearch")
        self.gridLayout_8.addWidget(self.btnSearch, 0, 2, 1, 1)
        self.txtSearchword = QtWidgets.QLineEdit(self.widgetSearch)
        self.txtSearchword.setMinimumSize(QtCore.QSize(0, 40))
        self.txtSearchword.setMaximumSize(QtCore.QSize(16777215, 40))
        self.txtSearchword.setStyleSheet("QLineEdit{\n"
"background-color: #393942;\n"
"color: #bababa;\n"
"border-top-left-radius : 20px;\n"
"border-bottom-left-radius : 20px;\n"
"font: 13pt \"微软雅黑\";\n"
"padding-left:15px;\n"
"}\n"
"QLineEdit:hover{\n"
"background-color: #373036;\n"
"border: 1px solid #393942;\n"
"}")
        self.txtSearchword.setObjectName("txtSearchword")
        self.gridLayout_8.addWidget(self.txtSearchword, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.widgetSearch, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(199, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 0, 3, 1, 1)
        self.widgetCrrlBtns = QtWidgets.QWidget(self.widgetTop)
        self.widgetCrrlBtns.setMinimumSize(QtCore.QSize(111, 0))
        self.widgetCrrlBtns.setStyleSheet("/*\n"
"border: 1px solid #393942;\n"
"*/")
        self.widgetCrrlBtns.setObjectName("widgetCrrlBtns")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widgetCrrlBtns)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.btnMinSize = QtWidgets.QPushButton(self.widgetCrrlBtns)
        self.btnMinSize.setMinimumSize(QtCore.QSize(16, 16))
        self.btnMinSize.setMaximumSize(QtCore.QSize(16, 16))
        self.btnMinSize.setText("")
        self.btnMinSize.setObjectName("btnMinSize")
        self.gridLayout_10.addWidget(self.btnMinSize, 0, 0, 1, 1)
        self.btnMaxSize = QtWidgets.QPushButton(self.widgetCrrlBtns)
        self.btnMaxSize.setMinimumSize(QtCore.QSize(16, 16))
        self.btnMaxSize.setMaximumSize(QtCore.QSize(16, 16))
        self.btnMaxSize.setText("")
        self.btnMaxSize.setObjectName("btnMaxSize")
        self.gridLayout_10.addWidget(self.btnMaxSize, 0, 1, 1, 1)
        self.btnClose = QtWidgets.QPushButton(self.widgetCrrlBtns)
        self.btnClose.setMinimumSize(QtCore.QSize(16, 16))
        self.btnClose.setMaximumSize(QtCore.QSize(16, 16))
        self.btnClose.setText("")
        self.btnClose.setObjectName("btnClose")
        self.gridLayout_10.addWidget(self.btnClose, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.widgetCrrlBtns, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.widgetTop, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(mainForm)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageWelcome = QtWidgets.QWidget()
        self.pageWelcome.setStyleSheet("")
        self.pageWelcome.setObjectName("pageWelcome")
        self.gridWelcome = QtWidgets.QGridLayout(self.pageWelcome)
        self.gridWelcome.setContentsMargins(0, 0, 0, 0)
        self.gridWelcome.setSpacing(0)
        self.gridWelcome.setObjectName("gridWelcome")
        self.stackedWidget.addWidget(self.pageWelcome)
        self.pageSearchResult = QtWidgets.QWidget()
        self.pageSearchResult.setStyleSheet("")
        self.pageSearchResult.setObjectName("pageSearchResult")
        self.gridLayout = QtWidgets.QGridLayout(self.pageSearchResult)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.pageSearchResult)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll = QtWidgets.QWidget()
        self.scroll.setGeometry(QtCore.QRect(0, 0, 81, 28))
        self.scroll.setObjectName("scroll")
        self.grid = QtWidgets.QGridLayout(self.scroll)
        self.grid.setSpacing(9)
        self.grid.setObjectName("grid")
        self.scrollArea.setWidget(self.scroll)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageSearchResult)
        self.pageDetail = QtWidgets.QWidget()
        self.pageDetail.setObjectName("pageDetail")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pageDetail)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widgetTop_2 = QtWidgets.QWidget(self.pageDetail)
        self.widgetTop_2.setMinimumSize(QtCore.QSize(0, 300))
        self.widgetTop_2.setMaximumSize(QtCore.QSize(16777215, 300))
        self.widgetTop_2.setObjectName("widgetTop_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widgetTop_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widgetDesc = QtWidgets.QWidget(self.widgetTop_2)
        self.widgetDesc.setStyleSheet("")
        self.widgetDesc.setObjectName("widgetDesc")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widgetDesc)
        self.gridLayout_7.setContentsMargins(12, -1, -1, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblStars = QtWidgets.QLabel(self.widgetDesc)
        self.lblStars.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblStars.setObjectName("lblStars")
        self.gridLayout_7.addWidget(self.lblStars, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widgetDesc)
        self.label_9.setMinimumSize(QtCore.QSize(0, 28))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widgetDesc)
        self.label_6.setMinimumSize(QtCore.QSize(0, 28))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widgetDesc)
        self.label_7.setMinimumSize(QtCore.QSize(0, 28))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 28))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widgetDesc)
        self.label_5.setMinimumSize(QtCore.QSize(40, 28))
        self.label_5.setMaximumSize(QtCore.QSize(40, 28))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.lblTitle = QtWidgets.QLabel(self.widgetDesc)
        self.lblTitle.setMinimumSize(QtCore.QSize(0, 50))
        self.lblTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lblTitle.setStyleSheet("font: 16pt \"微软雅黑\";")
        self.lblTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout_7.addWidget(self.lblTitle, 0, 0, 1, 2)
        self.lblTime = QtWidgets.QLabel(self.widgetDesc)
        self.lblTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblTime.setObjectName("lblTime")
        self.gridLayout_7.addWidget(self.lblTime, 2, 1, 1, 1)
        self.lblType = QtWidgets.QLabel(self.widgetDesc)
        self.lblType.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblType.setObjectName("lblType")
        self.gridLayout_7.addWidget(self.lblType, 3, 1, 1, 1)
        self.lblArea = QtWidgets.QLabel(self.widgetDesc)
        self.lblArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblArea.setObjectName("lblArea")
        self.gridLayout_7.addWidget(self.lblArea, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.widgetDesc, 0, 2, 1, 1)
        self.lblCover = QtWidgets.QLabel(self.widgetTop_2)
        self.lblCover.setMinimumSize(QtCore.QSize(210, 300))
        self.lblCover.setMaximumSize(QtCore.QSize(210, 300))
        self.lblCover.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.lblCover.setText("")
        self.lblCover.setObjectName("lblCover")
        self.gridLayout_6.addWidget(self.lblCover, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widgetTop_2)
        self.label_3.setMinimumSize(QtCore.QSize(15, 0))
        self.label_3.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widgetTop_2, 0, 0, 1, 1)
        self.widgetBottom = QtWidgets.QWidget(self.pageDetail)
        self.widgetBottom.setStyleSheet("")
        self.widgetBottom.setObjectName("widgetBottom")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetBottom)
        self.verticalLayout.setContentsMargins(30, 25, 30, 25)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widgetBottom)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollBtns = QtWidgets.QWidget()
        self.scrollBtns.setGeometry(QtCore.QRect(0, 0, 83, 30))
        self.scrollBtns.setObjectName("scrollBtns")
        self.gridBtns = QtWidgets.QGridLayout(self.scrollBtns)
        self.gridBtns.setObjectName("gridBtns")
        self.scrollArea_2.setWidget(self.scrollBtns)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.gridLayout_5.addWidget(self.widgetBottom, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageDetail)
        self.pageNoResult = QtWidgets.QWidget()
        self.pageNoResult.setObjectName("pageNoResult")
        self.label_2 = QtWidgets.QLabel(self.pageNoResult)
        self.label_2.setGeometry(QtCore.QRect(340, 170, 291, 151))
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.pageNoResult)
        self.gridLayout_4.addWidget(self.stackedWidget, 1, 0, 1, 1)

        self.retranslateUi(mainForm)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainForm)

    def retranslateUi(self, mainForm):
        _translate = QtCore.QCoreApplication.translate
        mainForm.setWindowTitle(_translate("mainForm", "看番神器"))
        self.btnGetAllLinks.setText(_translate("mainForm", "抓取链接"))
        self.btnOpenSource.setText(_translate("mainForm", "项目地址"))
        self.lblLastPlayEpisodeName.setText(_translate("mainForm", "无"))
        self.lblLastPlay.setText(_translate("mainForm", "最近一次播放："))
        self.btnAbout.setText(_translate("mainForm", "关于"))
        self.lblLastPlayEpisodeNum.setText(_translate("mainForm", "第0集"))
        self.btnBack.setText(_translate("mainForm", "返回"))
        self.comboSelectInterface.setItemText(0, _translate("mainForm", "接口1"))
        self.comboSelectInterface.setItemText(1, _translate("mainForm", "接口2"))
        self.btnSearch.setText(_translate("mainForm", "搜索"))
        self.txtSearchword.setText(_translate("mainForm", "我的青春恋爱物语"))
        self.lblStars.setText(_translate("mainForm", "演员："))
        self.label_9.setText(_translate("mainForm", "演员："))
        self.label_6.setText(_translate("mainForm", "类型："))
        self.label_7.setText(_translate("mainForm", "年代："))
        self.label_5.setText(_translate("mainForm", "地区："))
        self.lblTitle.setText(_translate("mainForm", "标题"))
        self.lblTime.setText(_translate("mainForm", "年代"))
        self.lblType.setText(_translate("mainForm", "类型"))
        self.lblArea.setText(_translate("mainForm", "地区"))
        self.label_2.setText(_translate("mainForm", "啥都没有"))
