# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingForm.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingForm(object):
    def setupUi(self, settingForm):
        settingForm.setObjectName("settingForm")
        settingForm.resize(375, 442)
        settingForm.setMinimumSize(QtCore.QSize(375, 375))
        settingForm.setMaximumSize(QtCore.QSize(375, 500))
        self.label = QtWidgets.QLabel(settingForm)
        self.label.setGeometry(QtCore.QRect(30, 30, 41, 21))
        self.label.setObjectName("label")
        self.txtUserName = QtWidgets.QLineEdit(settingForm)
        self.txtUserName.setGeometry(QtCore.QRect(80, 30, 211, 21))
        self.txtUserName.setObjectName("txtUserName")
        self.label_2 = QtWidgets.QLabel(settingForm)
        self.label_2.setGeometry(QtCore.QRect(30, 77, 41, 21))
        self.label_2.setObjectName("label_2")
        self.lblPlayer = QtWidgets.QLabel(settingForm)
        self.lblPlayer.setGeometry(QtCore.QRect(130, 80, 151, 41))
        self.lblPlayer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblPlayer.setWordWrap(True)
        self.lblPlayer.setObjectName("lblPlayer")
        self.lblIDM = QtWidgets.QLabel(settingForm)
        self.lblIDM.setGeometry(QtCore.QRect(130, 190, 151, 41))
        self.lblIDM.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblIDM.setWordWrap(True)
        self.lblIDM.setObjectName("lblIDM")
        self.label_5 = QtWidgets.QLabel(settingForm)
        self.label_5.setGeometry(QtCore.QRect(30, 187, 41, 21))
        self.label_5.setObjectName("label_5")
        self.groupBox = QtWidgets.QGroupBox(settingForm)
        self.groupBox.setGeometry(QtCore.QRect(20, 275, 331, 111))
        self.groupBox.setObjectName("groupBox")
        self.checkClosingWarning = QtWidgets.QCheckBox(self.groupBox)
        self.checkClosingWarning.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.checkClosingWarning.setObjectName("checkClosingWarning")
        self.checkPlaySound = QtWidgets.QCheckBox(self.groupBox)
        self.checkPlaySound.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.checkPlaySound.setObjectName("checkPlaySound")
        self.checkCheckUpdate = QtWidgets.QCheckBox(self.groupBox)
        self.checkCheckUpdate.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.checkCheckUpdate.setObjectName("checkCheckUpdate")
        self.btnCheckUpdate = QtWidgets.QPushButton(self.groupBox)
        self.btnCheckUpdate.setGeometry(QtCore.QRect(110, 80, 81, 23))
        self.btnCheckUpdate.setObjectName("btnCheckUpdate")
        self.btnChoosePlayer = QtWidgets.QToolButton(settingForm)
        self.btnChoosePlayer.setGeometry(QtCore.QRect(80, 77, 37, 21))
        self.btnChoosePlayer.setObjectName("btnChoosePlayer")
        self.btnChooseIDM = QtWidgets.QToolButton(settingForm)
        self.btnChooseIDM.setGeometry(QtCore.QRect(80, 187, 37, 21))
        self.btnChooseIDM.setObjectName("btnChooseIDM")
        self.btnTestPlayer = QtWidgets.QPushButton(settingForm)
        self.btnTestPlayer.setGeometry(QtCore.QRect(290, 77, 51, 23))
        self.btnTestPlayer.setObjectName("btnTestPlayer")
        self.btnTestIDM = QtWidgets.QPushButton(settingForm)
        self.btnTestIDM.setGeometry(QtCore.QRect(290, 187, 51, 23))
        self.btnTestIDM.setObjectName("btnTestIDM")
        self.btnFinished = QtWidgets.QPushButton(settingForm)
        self.btnFinished.setGeometry(QtCore.QRect(276, 400, 75, 23))
        self.btnFinished.setObjectName("btnFinished")
        self.label_6 = QtWidgets.QLabel(settingForm)
        self.label_6.setGeometry(QtCore.QRect(30, 240, 51, 21))
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(settingForm)
        self.comboBox.setGeometry(QtCore.QRect(90, 240, 91, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.btnTestPlayer2 = QtWidgets.QPushButton(settingForm)
        self.btnTestPlayer2.setGeometry(QtCore.QRect(290, 130, 51, 23))
        self.btnTestPlayer2.setObjectName("btnTestPlayer2")
        self.btnChoosePlayer2 = QtWidgets.QToolButton(settingForm)
        self.btnChoosePlayer2.setGeometry(QtCore.QRect(80, 130, 37, 21))
        self.btnChoosePlayer2.setObjectName("btnChoosePlayer2")
        self.lblPlayer2 = QtWidgets.QLabel(settingForm)
        self.lblPlayer2.setGeometry(QtCore.QRect(130, 133, 151, 41))
        self.lblPlayer2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblPlayer2.setWordWrap(True)
        self.lblPlayer2.setObjectName("lblPlayer2")
        self.label_3 = QtWidgets.QLabel(settingForm)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 61, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(settingForm)
        QtCore.QMetaObject.connectSlotsByName(settingForm)

    def retranslateUi(self, settingForm):
        _translate = QtCore.QCoreApplication.translate
        settingForm.setWindowTitle(_translate("settingForm", "设置"))
        self.label.setText(_translate("settingForm", "用户名"))
        self.label_2.setText(_translate("settingForm", "播放器"))
        self.lblPlayer.setText(_translate("settingForm", "无"))
        self.lblIDM.setText(_translate("settingForm", "无"))
        self.label_5.setText(_translate("settingForm", "下载器"))
        self.groupBox.setTitle(_translate("settingForm", "开关"))
        self.checkClosingWarning.setText(_translate("settingForm", "关闭窗口警告"))
        self.checkPlaySound.setText(_translate("settingForm", "播放音效"))
        self.checkCheckUpdate.setText(_translate("settingForm", "自动检查更新"))
        self.btnCheckUpdate.setText(_translate("settingForm", "点我手动检查"))
        self.btnChoosePlayer.setText(_translate("settingForm", "..."))
        self.btnChooseIDM.setText(_translate("settingForm", "..."))
        self.btnTestPlayer.setText(_translate("settingForm", "测试"))
        self.btnTestIDM.setText(_translate("settingForm", "测试"))
        self.btnFinished.setText(_translate("settingForm", "完成"))
        self.label_6.setText(_translate("settingForm", "默认接口"))
        self.comboBox.setItemText(0, _translate("settingForm", "接口1"))
        self.btnTestPlayer2.setText(_translate("settingForm", "测试"))
        self.btnChoosePlayer2.setText(_translate("settingForm", "..."))
        self.lblPlayer2.setText(_translate("settingForm", "无"))
        self.label_3.setText(_translate("settingForm", "备用播放器"))
